AWSTemplateFormatVersion : '2010-09-09'
# Transform of AWS::Severless-2016-10-31 identifies the template file as an AWS SAM template file
# this distinguishes it from other Cloud Formation templates
# essentially, an AWS Cloud Formation Transform specifies the macros that AWS will use to parse the template
# there are other templates available
Transform: AWS::Serverless-2016-10-31
Description: The SAM template for our backend resources.

# Here is the Resources section, which can specify both SAM resources and Cloud Formation resources
# This section, along with the Transform section, is required
Resources:
  BagEndApiGateway:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod
# Details about the myDateTimeFunction Lambda function
# This is the main Lambda function in this template. The other two functions are used to run tests on the code before and after deployment.
  ProcessCounter:
    # The AWS::Severless::Function type creates a Lambda function, IAM role for that function, and event mappings
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: processCounter.py
      # The handler is the function that is called to begin execution. This is required if deployment package is .zip
      Handler: processCounter.lambda_handler
      # runtime also required if deployment package is .zip
      Runtime: python3.9
# Instructs your myDateTimeFunction is published to an alias named "live".
      # Lambda aliases are pointers to a specific function versions      
      AutoPublishAlias: live
# Grants this function permission to call lambda:InvokeFunction
      Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "lambda:InvokeFunction"
            Resource: '*'
      DeploymentPreference:
# Specifies the deployment configuration      
          Type: AllAtOnce # this will make GitHub Actions complete faster, which is good for this project
# This adds a "GET" endpoint to our API Gateway
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: BagEndApiGateway
  CountTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE