name: deploy-aws-sam
run-name: ${{ github.actor }} is deploying backend resources with AWS SAM
on: [push]
jobs:
  deploy-aws-sam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run Python tests
        run: python -m unittest handlerTests.py
          
      - name: Package AWS SAM file
        run: sam package --template-file sam-template.yml --output-template-file package.yml --s3-bucket sam-package-bagend

      - name: Deploy AWS SAM file
        run: sam deploy --template-file package.yml --stack-name bagend-app --capabilities CAPABILITY_IAM